name = "noaa-jp"
pages_build_output_dir = "public"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "noaa-inquiries"
database_id = "2dbc54b2-282f-43f3-ab3d-94ed654ebe80"

[vars]
CONTACT_FROM_ADDRESS = "onboarding@resend.dev"
CONTACT_TO_ADDRESS = "hasegawa@noaa.jp"
